#!/usr/bin/env bash
# revert-last-merge.sh — one command to undo a merged PR.
#
#   .github/agent-gate/revert-last-merge.sh [<pr-number>|<merge-sha>|last] [--deploy] [--reason TEXT]
#
# 1. Resolves the merge commit (a PR number, a SHA, or `last` = newest merge on integration).
# 2. In a throwaway worktree, branches `revert/<sha7>` from origin/integration and runs
#    `git revert -m 1 <merge>` (the repo merges with merge commits, so -m 1 is exact).
# 3. Pushes and opens a PR whose body carries the agent-author marker, a filled Risk & rollback
#    section and `<!-- agent-revert of=<sha> -->`. agent-gate verifies that marker against git
#    (clean inverse of a merge on integration, nothing else) and waives the agent review, so the
#    revert merges as soon as CI is green: `gh pr merge <n> --merge --match-head-commit <sha>`.
# 4. --deploy (on the live host only) rolls production back NOW instead of waiting for the
#    merge: the fast image rollback when the reverted merge is what is running, otherwise a
#    rebuild of the revert commit. See scripts/deploy/deploy.sh.
#
# Never touches the caller's checkout or the live checkout's branch except via --deploy.
# Exit codes: 0 ok, 1 usage/lookup error, 2 the revert conflicts (resolve by hand; the gate then
# requires a normal agent review because the result is no longer a pure inverse).
set -euo pipefail

REPO="${REVERT_REPO:-$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)}"
BASE="${REVERT_BASE:-integration}"
REMOTE="${REVERT_REMOTE:-origin}"
GH="${REVERT_GH:-gh}"
DEPLOY="${REVERT_DEPLOY_SCRIPT:-$REPO/scripts/deploy/deploy.sh}"

target="last"; do_deploy=0; reason=""
while (($#)); do
  case "$1" in
    --deploy) do_deploy=1 ;;
    --reason) reason="${2:?--reason needs text}"; shift ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    -*) echo "unknown option: $1" >&2; exit 1 ;;
    *) target="$1" ;;
  esac
  shift
done

git -C "$REPO" fetch --quiet "$REMOTE" "+refs/heads/$BASE:refs/remotes/$REMOTE/$BASE"
base_ref="refs/remotes/$REMOTE/$BASE"

title=""
if [[ "$target" == "last" ]]; then
  merge="$(git -C "$REPO" rev-list --first-parent --merges -n1 "$base_ref")"
elif [[ "$target" =~ ^[0-9]+$ ]]; then
  merge="$("$GH" pr view "$target" --json mergeCommit,state --jq 'select(.state=="MERGED") | .mergeCommit.oid')"
  [[ -n "$merge" ]] || { echo "PR #$target is not merged" >&2; exit 1; }
else
  merge="$(git -C "$REPO" rev-parse --verify --quiet "$target^{commit}")" || { echo "unknown commit: $target" >&2; exit 1; }
fi
[[ -n "$merge" ]] || { echo "no merge commit found on $BASE" >&2; exit 1; }
if [[ "$(git -C "$REPO" rev-list --parents -n1 "$merge" | wc -w)" -ne 3 ]]; then
  echo "$merge is not a merge commit; this tool reverts merged PRs only" >&2; exit 1
fi
git -C "$REPO" merge-base --is-ancestor "$merge" "$base_ref" || { echo "$merge is not on $BASE" >&2; exit 1; }
short="${merge:0:7}"
subject="$(git -C "$REPO" log -1 --format=%s "$merge")"
pr_number="$(sed -nE 's/^Merge pull request #([0-9]+) .*/\1/p' <<<"$subject")"
if [[ -n "$pr_number" ]]; then
  title="$("$GH" pr view "$pr_number" --json title --jq .title 2>/dev/null || true)"
fi
title="${title:-$subject}"
branch="revert/$short"

existing="$("$GH" pr list --head "$branch" --state open --json url --jq '.[0].url // empty' 2>/dev/null || true)"
if [[ -n "$existing" ]]; then
  echo "revert PR already open: $existing"
  pr_url="$existing"
else
  wt="$(mktemp -d)"
  cleanup() { git -C "$REPO" worktree remove --force "$wt" >/dev/null 2>&1 || rm -rf "$wt"; }
  trap cleanup EXIT
  git -C "$REPO" worktree add --quiet --detach "$wt" "$base_ref"
  git -C "$wt" checkout --quiet -B "$branch"
  if ! git -C "$wt" revert --no-edit -m 1 "$merge" >/dev/null; then
    git -C "$wt" revert --abort || true
    echo "git revert -m 1 $short conflicts with later changes on $BASE; revert by hand" >&2
    exit 2
  fi
  git -C "$wt" push --quiet --force-with-lease "$REMOTE" "HEAD:refs/heads/$branch"

  harness="${AGENT_HARNESS:-script}"; model="${AGENT_MODEL:-revert-last-merge}"
  session="${AGENT_SESSION:-revert-$short-$(date -u +%Y%m%dT%H%M%SZ)}"
  body="$(mktemp)"
  cat >"$body" <<EOF
<!-- agent-author harness=$harness model=$model session=$session -->
<!-- agent-revert of=$merge -->

## Summary

Reverts $short ("$title")${pr_number:+ from #$pr_number} with \`git revert -m 1\`.
${reason:+
Reason: $reason
}
## Risk & rollback

- **What could break:** whatever $short fixed or added is removed again; later PRs that build on it may need follow-up.
- **How verified:** agent-gate checks this branch is exactly the inverse of merge $short (git patch-id), and CI runs on the result.
- **How to revert:** revert this revert: \`scripts/revert-last-merge.sh <this PR number>\`.

## Verification checklist

- [x] Pure \`git revert -m 1\`, generated by scripts/revert-last-merge.sh
- [ ] CI green on the head commit

If agent-gate is still pending after CI finishes: \`gh workflow run agent-gate.yml -f pr=<this PR>\`.
EOF
  pr_url="$("$GH" pr create --base "$BASE" --head "$branch" --title "Revert \"$title\"" --body-file "$body")"
  rm -f "$body"
  echo "opened $pr_url"
  # GITHUB_TOKEN-authored pushes/PRs trigger no workflows; dispatch the ones the gate needs.
  if [[ "${GITHUB_ACTIONS:-}" == "true" ]]; then
    for wf in ${REVERT_DISPATCH_WORKFLOWS:-tests.yml}; do "$GH" workflow run "$wf" --ref "$branch" || true; done
    "$GH" workflow run agent-gate.yml -f pr="${pr_url##*/}" || true
  fi
fi

if ((do_deploy)); then
  revert_sha="$(git -C "$REPO" ls-remote "$REMOTE" "refs/heads/$branch" | cut -f1)"
  bash "$DEPLOY" --revert-of "$merge" --ref "$revert_sha"
fi
echo "$pr_url"
